services:
  - type: web
    name: ecoscan
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers=1 --threads=1 --timeout 200"
    envVars:
      PYTHON_VERSION: 3.10
