services:
  - type: web
    name: ecoscan
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn app:app --timeout 200 --workers 1 --threads 8 --preload
    plan: free
    envVars:
      PYTHON_VERSION: 3.10
